### ISSUE TITLE
Get coordinates

### ISSUE THREAD

**Issue by slavendam** [ebaauw/fp2-proxy#1]
Great work!

Is it possible to get precise coordinates (distance and angle) from FP2 sensor using this proxy?
I'm more interested in precise location and not just zones which is provided in regular integrations.

Thanks!

**Comment by ebaauw** [comment]
No, the sensor doesn’t expose these to HomeKit.

As far as I’ve been able to determine, the Aqara app seems to get this info through the Aqara cloud, and not directly from the sensor.
